# Generated by Django 4.2.28 on 2026-07-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KaraReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_key",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="کلید گزارش"
                    ),
                ),
                (
                    "report_title",
                    models.CharField(max_length=255, verbose_name="عنوان گزارش"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(db_index=True, verbose_name="زمان دریافت"),
                ),
                ("raw_data", models.JSONField(verbose_name="داده خام")),
                (
                    "rows_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد ردیف"),
                ),
            ],
            options={
                "verbose_name": "اسنپ\u200cشات گزارش کارا",
                "verbose_name_plural": "اسنپ\u200cشات\u200cهای گزارش کارا",
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["report_key", "-fetched_at"],
                        name="reports_kar_report__f1a6e4_idx",
                    )
                ],
            },
        ),
    ]
