# Generated by Django 4.2.28 on 2026-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardRefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "آماده"),
                            ("running", "در حال اجرا"),
                            ("success", "موفق"),
                            ("error", "خطا"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("reports_refreshed", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "triggered_by",
                    models.CharField(
                        default="auto", max_length=50, verbose_name="منبع"
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ بروزرسانی",
                "verbose_name_plural": "لاگ\u200cهای بروزرسانی",
                "ordering": ["-started_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="karareportsnapshot",
            name="reports_kar_report__f1a6e4_idx",
        ),
        migrations.AddField(
            model_name="karareportsnapshot",
            name="personnel_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="کد پرسنلی",
            ),
        ),
        migrations.AddField(
            model_name="karareportsnapshot",
            name="personnel_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="نام پرسنلی"
            ),
        ),
        migrations.AddIndex(
            model_name="karareportsnapshot",
            index=models.Index(
                fields=["report_key", "personnel_code", "-fetched_at"],
                name="reports_kar_report__57e781_idx",
            ),
        ),
    ]
