# Generated by Django 4.2.28 on 2026-07-30 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reports.constants


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_dashboardrefreshlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBusinessMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_date", models.CharField(db_index=True, max_length=20)),
                (
                    "source_report",
                    models.CharField(default="visitor_sale", max_length=100),
                ),
                (
                    "total_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "total_pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("order_count", models.IntegerField(default=0)),
                (
                    "distribution_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "sale_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "settlement_remainder",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("active_visitors", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-metric_date"],
            },
        ),
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DistributionReversionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "partner_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("order_date", models.CharField(blank=True, default="", max_length=20)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HeadVisitorSaleSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                ("head_visitor_code", models.CharField(db_index=True, max_length=50)),
                (
                    "head_visitor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "total_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "total_pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("order_count", models.IntegerField(default=0)),
                (
                    "distribution_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "sale_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "settlement_remainder",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="KaraConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="اتصال اصلی کارا", max_length=120)),
                ("base_url", models.URLField(max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=120)),
                (
                    "secret_reference",
                    models.CharField(
                        blank=True,
                        default="env:KARA_PASSWORD",
                        help_text="مرجع رمز؛ مثلاً env:KARA_PASSWORD",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "connection_status",
                    models.CharField(
                        db_index=True,
                        default=reports.constants.ConnectionStatus["UNKNOWN"],
                        max_length=32,
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "اتصال کارا",
                "verbose_name_plural": "اتصالات کارا",
            },
        ),
        migrations.CreateModel(
            name="KaraRawResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_key", models.CharField(db_index=True, max_length=100)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("payload", models.JSONField()),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "verbose_name": "پاسخ خام کارا",
                "verbose_name_plural": "پاسخ\u200cهای خام کارا",
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="KaraSyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_key", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("success", "success"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default=reports.constants.SyncStatus["PENDING"],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_from_date",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "requested_to_date",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("received_count", models.PositiveIntegerField(default=0)),
                ("inserted_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("triggered_by", models.CharField(default="manual", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "وظیفه همگام\u200cسازی",
                "verbose_name_plural": "وظایف همگام\u200cسازی",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ManagementAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("warning", "warning"),
                            ("critical", "critical"),
                        ],
                        db_index=True,
                        default=reports.constants.AlertSeverity["INFO"],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("metric", models.CharField(blank=True, default="", max_length=100)),
                (
                    "current_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "expected_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("entity", models.CharField(blank=True, default="", max_length=255)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("acknowledged", "acknowledged"),
                            ("closed", "closed"),
                        ],
                        db_index=True,
                        default=reports.constants.AlertStatus["OPEN"],
                        max_length=20,
                    ),
                ),
                (
                    "detail_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "هشدار مدیریتی",
                "verbose_name_plural": "هشدارهای مدیریتی",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddField(
            model_name="karareportsnapshot",
            name="content_checksum",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="karareportsnapshot",
            name="period_from",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="karareportsnapshot",
            name="period_to",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.CreateModel(
            name="VisitorSaleSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                ("visitor_code", models.CharField(db_index=True, max_length=50)),
                (
                    "visitor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "head_visitor_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "head_visitor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "total_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "total_pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("order_count", models.IntegerField(default=0)),
                ("partner_count", models.IntegerField(default=0)),
                (
                    "distribution_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "sale_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "settlement_remainder",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("source_key", models.CharField(blank=True, default="", max_length=50)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "last_sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_rows",
                        to="reports.karasyncjob",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسنپ\u200cشات فروش ویزیتور",
                "verbose_name_plural": "اسنپ\u200cشات\u200cهای فروش ویزیتور",
            },
        ),
        migrations.CreateModel(
            name="StuffGroupSaleSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("zone", models.CharField(blank=True, default="", max_length=120)),
                (
                    "pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "not_pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("order_count", models.IntegerField(default=0)),
                (
                    "distribution_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "sale_reversion",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stuff_group_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleReversionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reversion_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "partner_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reversion_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("order_date", models.CharField(blank=True, default="", max_length=20)),
                (
                    "reversion_date",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_reversion_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KaraSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(default="info", max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reports.karasyncjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="karasyncjob",
            index=models.Index(
                fields=["report_key", "-started_at"],
                name="reports_kar_report__290844_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="karasyncjob",
            index=models.Index(
                fields=["status", "-started_at"], name="reports_kar_status_2d6ede_idx"
            ),
        ),
        migrations.AddField(
            model_name="kararawresponse",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_responses",
                to="reports.karasyncjob",
            ),
        ),
        migrations.AddField(
            model_name="headvisitorsalesnapshot",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_visitor_rows",
                to="reports.karareportsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="headvisitorsalesnapshot",
            name="sync_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.karasyncjob",
            ),
        ),
        migrations.AddField(
            model_name="distributionreversionsnapshot",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution_reversion_rows",
                to="reports.karareportsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="distributionreversionsnapshot",
            name="sync_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.karasyncjob",
            ),
        ),
        migrations.AddField(
            model_name="dailybusinessmetric",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.karareportsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="karareportsnapshot",
            name="sync_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snapshots",
                to="reports.karasyncjob",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsalesnapshot",
            index=models.Index(
                fields=["visitor_code", "-last_seen_at"],
                name="reports_vis_visitor_441fb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsalesnapshot",
            index=models.Index(
                fields=["head_visitor_code", "-last_seen_at"],
                name="reports_vis_head_vi_035984_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitorsalesnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "visitor_code"),
                name="uniq_visitor_sale_per_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="stuffgroupsalesnapshot",
            index=models.Index(
                fields=["group_name", "-last_seen_at"],
                name="reports_stu_group_n_f5db8c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="headvisitorsalesnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "head_visitor_code"),
                name="uniq_head_visitor_sale_per_snapshot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailybusinessmetric",
            unique_together={("metric_date", "source_report")},
        ),
    ]
