# Generated by Django 4.2.28 on 2026-07-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_analytics_layer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_code", models.CharField(db_index=True, max_length=50)),
                (
                    "order_pre_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("order_date", models.CharField(blank=True, default="", max_length=20)),
                (
                    "partner_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "visitor_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "order_final_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "finalized_cost",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "sale_reversion_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("stuffs_quantity_sum", models.IntegerField(default=0)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_order_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfitDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(db_index=True, unique=True)),
                ("invoice_count", models.IntegerField(default=0)),
                (
                    "invoice_revenue",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "finalized_cost",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "sale_reversion_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gross_margin_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profit_daily_metrics",
                        to="reports.karareportsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاخص سود روزانه",
                "verbose_name_plural": "شاخص\u200cهای سود روزانه",
                "ordering": ["-business_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(db_index=True)),
                ("stuff_code", models.CharField(db_index=True, max_length=50)),
                (
                    "stuff_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stuff_group_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sale_quantity", models.IntegerField(default=0)),
                (
                    "sale_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("sale_reversion_quantity", models.IntegerField(default=0)),
                (
                    "sale_reversion_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_daily_metrics",
                        to="reports.karareportsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاخص روزانه کالا",
                "verbose_name_plural": "شاخص\u200cهای روزانه کالا",
                "ordering": ["-business_date", "-pure_sale"],
            },
        ),
        migrations.CreateModel(
            name="SaleStuffSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stuff_code", models.CharField(db_index=True, max_length=50)),
                (
                    "stuff_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stuff_group_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "stuff_sub_group_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sale_quantity", models.IntegerField(default=0)),
                (
                    "sale_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("sale_reversion_quantity", models.IntegerField(default=0)),
                (
                    "sale_reversion_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_stuff_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stuff_group_name", "-last_seen_at"],
                        name="reports_sal_stuff_g_215e89_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="salestuffsnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "stuff_code"), name="uniq_sale_stuff_per_snapshot"
            ),
        ),
        migrations.AddIndex(
            model_name="saleordersnapshot",
            index=models.Index(
                fields=["visitor_code", "-last_seen_at"],
                name="reports_sal_visitor_64eba4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleordersnapshot",
            index=models.Index(
                fields=["order_date"], name="reports_sal_order_d_78438d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleordersnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "order_code"), name="uniq_sale_order_per_snapshot"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productdailymetric",
            unique_together={("business_date", "stuff_code")},
        ),
    ]
