# Generated by Django 4.2.28 on 2026-07-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_monthly_sale_and_stuff_group_detail"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="monthlysaledetailsnapshot",
            new_name="reports_mon_fiscal__a3fe5e_idx",
            old_name="reports_mon_fiscal__idx",
        ),
        migrations.RenameIndex(
            model_name="stuffgroupsalesnapshot",
            new_name="reports_stu_stuff_c_395b5f_idx",
            old_name="reports_stu_stuff_c_idx",
        ),
    ]
