# Generated by Django 4.2.28 on 2026-07-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0008_rename_reports_mon_fiscal__idx_reports_mon_fiscal__a3fe5e_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivableDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(db_index=True, unique=True)),
                ("bucket_totals", models.JSONField(blank=True, default=dict)),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("row_count", models.IntegerField(default=0)),
                (
                    "partner_balance_total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("partner_count", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivable_daily_metrics",
                        to="reports.karareportsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاخص روزانه مطالبات",
                "verbose_name_plural": "شاخص\u200cهای روزانه مطالبات",
                "ordering": ["-business_date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfitLossMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_from",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "period_to",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                ("business_date", models.DateField(db_index=True, unique=True)),
                (
                    "net_pure_sale",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "cost_of_goods_sold",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "operating_profit",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gross_margin_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("line_items", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profit_loss_metrics",
                        to="reports.karareportsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاخص سود و زیان شرکت",
                "verbose_name_plural": "شاخص\u200cهای سود و زیان شرکت",
                "ordering": ["-business_date", "-period_to"],
            },
        ),
        migrations.CreateModel(
            name="AccountBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_code", models.CharField(db_index=True, max_length=50)),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "partner_legal_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("monthly_balances", models.JSONField(blank=True, default=dict)),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_balance_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "مانده حساب مشتری",
                "verbose_name_plural": "مانده\u200cهای حساب مشتری",
            },
        ),
        migrations.CreateModel(
            name="ReceivableAgingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_key", models.CharField(db_index=True, max_length=120)),
                (
                    "visitor_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "partner_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "city_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "route_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("bucket_amounts", models.JSONField(blank=True, default=dict)),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivable_aging_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیف سنی معوقات",
                "verbose_name_plural": "ردیف\u200cهای سنی معوقات",
                "indexes": [
                    models.Index(
                        fields=["visitor_code", "-last_seen_at"],
                        name="reports_rec_visitor_e6266c_idx",
                    ),
                    models.Index(
                        fields=["city_name", "-last_seen_at"],
                        name="reports_rec_city_na_a3c31a_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="receivableagingsnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "row_key"),
                name="uniq_receivable_aging_per_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalancesnapshot",
            index=models.Index(
                fields=["partner_code", "-last_seen_at"],
                name="reports_acc_partner_cedf2e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbalancesnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "partner_code"),
                name="uniq_account_balance_per_snapshot",
            ),
        ),
    ]
