# Generated by Django 4.2.28 on 2026-07-30 12:57

from django.db import migrations, models
import reports.constants


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_receivables_and_pnl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("running", "در حال اجرا"),
                    ("success", "موفق"),
                    ("partial", "ناقص"),
                    ("failed", "ناموفق"),
                    ("cancelled", "لغو شده"),
                ],
                db_index=True,
                default=reports.constants.SyncStatus["PENDING"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="backfillrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("running", "در حال اجرا"),
                    ("success", "موفق"),
                    ("partial", "ناقص"),
                    ("failed", "ناموفق"),
                    ("cancelled", "لغو شده"),
                ],
                db_index=True,
                default=reports.constants.SyncStatus["PENDING"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="karasyncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("running", "در حال اجرا"),
                    ("success", "موفق"),
                    ("partial", "ناقص"),
                    ("failed", "ناموفق"),
                    ("cancelled", "لغو شده"),
                ],
                db_index=True,
                default=reports.constants.SyncStatus["PENDING"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="managementalert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "اطلاع"),
                    ("warning", "هشدار"),
                    ("critical", "بحرانی"),
                ],
                db_index=True,
                default=reports.constants.AlertSeverity["INFO"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="managementalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("acknowledged", "تأییدشده"),
                    ("closed", "بسته"),
                ],
                db_index=True,
                default=reports.constants.AlertStatus["OPEN"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userkaraidentity",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "مدیر سیستم"),
                    ("executive_manager", "مدیر ارشد"),
                    ("sales_manager", "مدیر فروش"),
                    ("sales_supervisor", "سرپرست فروش"),
                    ("salesperson", "ویزیتور"),
                    ("viewer", "بازدیدکننده"),
                    ("tv_display", "نمایش سالن"),
                ],
                db_index=True,
                default=reports.constants.KaraRole["VIEWER"],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userkaraidentity",
            name="supervisor_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="برای سرپرست: کد سرپرست در کارا",
                max_length=50,
            ),
        ),
    ]
