# Generated by Django 5.1.15 on 2026-08-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_alter_analyticsperiod_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bale_user_id", models.BigIntegerField(db_index=True, unique=True)),
                ("flow_state", models.CharField(blank=True, default="", max_length=50)),
                ("nav_stack", models.JSONField(blank=True, default=list)),
                ("menu_message_id", models.BigIntegerField(blank=True, null=True)),
                ("menu_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "وضعیت گفتگوی ربات",
                "verbose_name_plural": "وضعیت\u200cهای گفتگوی ربات",
            },
        ),
        migrations.CreateModel(
            name="BotInvoiceWatchState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "visitor_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "status_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ردیاب وضعیت فاکتور",
                "verbose_name_plural": "ردیابی وضعیت فاکتورها",
            },
        ),
        migrations.CreateModel(
            name="BaleUserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bale_user_id", models.BigIntegerField(db_index=True, unique=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("failed_login_count", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bale_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "هویت بله",
                "verbose_name_plural": "هویت\u200cهای بله",
            },
        ),
        migrations.CreateModel(
            name="BotActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bale_user_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ فعالیت ربات",
                "verbose_name_plural": "لاگ\u200cهای فعالیت ربات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotNotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_code", models.CharField(db_index=True, max_length=100)),
                (
                    "visitor_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                ("old_value", models.CharField(blank=True, default="", max_length=255)),
                ("new_value", models.CharField(blank=True, default="", max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رویداد اعلان ربات",
                "verbose_name_plural": "رویدادهای اعلان ربات",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "event_type",
                            "entity_type",
                            "entity_code",
                            "new_value",
                        ),
                        name="uniq_bot_notification_event",
                    )
                ],
            },
        ),
    ]
