# Generated by Django 4.2.30 on 2026-08-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0013_bot_user_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="botusernotification",
            new_name="reports_bot_bale_us_5ee35d_idx",
            old_name="reports_bot_bale_us_8f3a21_idx",
        ),
        migrations.RenameIndex(
            model_name="botusernotification",
            new_name="reports_bot_bale_us_18aa20_idx",
            old_name="reports_bot_bale_us_4c9e12_idx",
        ),
    ]
