# Generated by Django 5.1.15 on 2026-08-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0014_rename_reports_bot_bale_us_8f3a21_idx_reports_bot_bale_us_5ee35d_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderLineSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_key", models.CharField(db_index=True, max_length=160)),
                ("order_code", models.CharField(db_index=True, max_length=50)),
                (
                    "order_pre_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("order_date", models.CharField(blank=True, default="", max_length=20)),
                (
                    "partner_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "visitor_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stuff_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "stuff_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stuff_group_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stuff_sub_group_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("unit_name", models.CharField(blank=True, default="", max_length=120)),
                ("package_quantity", models.IntegerField(default=0)),
                ("stuff_quantity", models.IntegerField(default=0)),
                (
                    "unit_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "line_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "order_final_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_order_line_rows",
                        to="reports.karareportsnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.karasyncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیف اقلام فاکتور",
                "verbose_name_plural": "ردیف\u200cهای اقلام فاکتور",
                "indexes": [
                    models.Index(
                        fields=["order_code", "snapshot"],
                        name="reports_sal_order_c_2b57ca_idx",
                    ),
                    models.Index(
                        fields=["visitor_code", "order_code"],
                        name="reports_sal_visitor_d85d77_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "row_key"),
                        name="uniq_sale_order_line_per_snapshot",
                    )
                ],
            },
        ),
    ]
