# Generated by Django 4.2.30 on 2026-08-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_sale_order_lines"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleordersnapshot",
            options={"verbose_name": "فاکتور", "verbose_name_plural": "فاکتورها"},
        ),
    ]
