# Generated by Django 5.1.15 on 2026-08-14 10:47

from django.db import migrations, models


def backfill_pre_order_status(apps, schema_editor):
    SaleOrderSnapshot = apps.get_model("reports", "SaleOrderSnapshot")
    from reports.services.invoices import derive_pre_order_status, order_status_row

    batch = []
    for order in SaleOrderSnapshot.objects.iterator(chunk_size=500):
        row = order_status_row(order)
        status = derive_pre_order_status(row)
        if status != order.pre_order_status:
            order.pre_order_status = status
            batch.append(order)
        if len(batch) >= 500:
            SaleOrderSnapshot.objects.bulk_update(batch, ["pre_order_status"])
            batch.clear()
    if batch:
        SaleOrderSnapshot.objects.bulk_update(batch, ["pre_order_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0016_alter_saleordersnapshot_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleordersnapshot",
            name="pre_order_status",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.RunPython(backfill_pre_order_status, migrations.RunPython.noop),
    ]
