"""Conversation flow states — no secrets stored here."""

from __future__ import annotations

WAITING_PERSONNEL_CODE = "WAITING_PERSONNEL_CODE"
WAITING_PASSWORD = "WAITING_PASSWORD"
WAITING_INVOICE_NUMBER = "WAITING_INVOICE_NUMBER"
WAITING_CUSTOMER_NAME = "WAITING_CUSTOMER_NAME"
LOGOUT_CONFIRM = "LOGOUT_CONFIRM"
